-- ============================================================
-- CRIAR TABELA: producoes
-- Execute este SQL no Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS producoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    receita_id BIGINT,
    nome_receita TEXT NOT NULL,
    quantidade_lotes INTEGER NOT NULL DEFAULT 1,
    total_unidades INTEGER NOT NULL DEFAULT 0,
    data_producao DATE NOT NULL DEFAULT CURRENT_DATE,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE producoes ENABLE ROW LEVEL SECURITY;

-- Política: usuário só vê suas próprias produções
CREATE POLICY "Usuários veem suas próprias produções"
    ON producoes FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Usuários inserem suas próprias produções"
    ON producoes FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários atualizam suas próprias produções"
    ON producoes FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Usuários deletam suas próprias produções"
    ON producoes FOR DELETE
    USING (auth.uid() = user_id);

-- Índices
CREATE INDEX IF NOT EXISTS idx_producoes_user_id ON producoes(user_id);
CREATE INDEX IF NOT EXISTS idx_producoes_data ON producoes(data_producao);
CREATE INDEX IF NOT EXISTS idx_producoes_receita ON producoes(receita_id);

SELECT '✅ Tabela producoes criada com RLS!' AS resultado;
